
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sdo
    ports:
      - "5454:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - sdo_network

networks:
  sdo_network:
    driver: bridge