###
GET http://localhost:8040/user_data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0dWRlbnQiLCJyb2xldHlwZSI6InN0dWRlbnQiLCJzdHVkeWdyb3VwIjoiMjMxLTMzNSIsImV4cCI6MTczNjI2MzY4Mn0.G5HjmEyKSfTAUblqeyNl-pb60_j4dBf91MlmP-IkOoY
Content-Type: application/json